### ISSUE TITLE
Switching to tokio_util and exposing futures_stream

### ISSUE THREAD

**Issue by whypet** [zyansheep/rkyv_codec#4]
Hi,
I came across this crate a while ago and am now using it for my project to have rkyv over TCP. However, I saw that one of the dependencies used, `futures_codec`, hasn't been maintained for a while now and it looks like it has the same functionality as `tokio_util`, which I use.

It seems like these crates are incompatible with each other as I was getting trait bound errors that looked like conflicting implementations, so in the meantime I have created a fork over at https://github.com/whypet/rkyv_codec to be able to integrate this crate within my project that uses Tokio. However I had to remove some code concerning `CborCodec`--I'm not exactly sure what it is used for, so I don't feel like my changes are complete enough to create a pull request instead. Would moving over to `tokio_util` be viable?

Furthermore, I wanted to make use of `Framed` in my project but noticed that the module providing the stream codec implementation, `futures_stream`, wasn't exposed nor was any of it re-exported, so I made it a public module in my fork. If this was unintentional, I think that change should be reflected here too.

(This also might be unrelated, but concerning #3, doesn't Framed already cover this use case? I'm open to contributing if needed.)

Thanks for making this crate, it saved me a lot of time.

**Comment by zyansheep** [comment]
Thanks for the issue!
Its been awhile since I did anything in this repo, but IIRC the goal was to provide general codec support and a wrapper for easy use with future's AsyncRead/AsyncWrite ecosystem specifically as I used async-std primarily and the futures asyncread/asyncwrite ecosystem doesn't provide buffer management like tokio does. Afaik it should be really easy to implement a custom tokio_util Encoder/Decoder or just use a BytesCodec with tokio's asyncread/asyncwrite using the bytes API (`archive_sink_bytes` and `archive_stream_bytes`), the futures_stream module is solely for the futures ecosystem AsyncRead/AsyncWrite and I think will be incompatible with tokio.

CborCodec is just used for dev benchmarking :sweat_smile:.

Although if you do implement a tokio_utils Encoder/Decoder, feel free to make a PR!

**Comment by whypet** [comment]
Thanks for getting back to me quickly! I didn't know much about async-std before creating this issue, I now see why this crate is incompatible with Tokio. I'll likely write my own implementation at some point then, considering it's easier in Tokio, I had tried this before but encountered a weird bug so I just switched to this crate instead. I'll make a PR for another Encoder/Decoder that uses `tokio_util` if I get around to it.
